### ISSUE TITLE
Won't work with Magisk 22

### ISSUE THREAD

**Issue by PeterNjeim** [mirsella/magisk-fusermount-bin#1]
Magisk says 

> Copying zip to temp directory
> Unzip error

Looking at Magisk's [code](https://github.com/topjohnwu/Magisk/blob/master/app/src/main/java/com/topjohnwu/magisk/core/tasks/FlashZip.kt), it says "Unzip error" when `updater-script` doesn't contain `#MAGISK` except it clearly does contain that. So I don't know what's going wrong.

**Comment by mirsella** [comment]
honestly I don't know as I am on magisk 22 and it work. maybe try to flash canary ?

**Comment by PeterNjeim** [comment]
Yeah it works now. I had the files inside a folder inside the zip, instead of the root of the zip just being the files themselves.

**Comment by mirsella** [comment]
hapenned to me multiple time while trying to do my vim module :)

btw I made a release.zip ready to flash if you want for the next time
