### ISSUE TITLE
Module does not install with Magisk 23.0 Error: 255

### ISSUE THREAD

**Issue by ioogithub** [mirsella/magisk-fusermount-bin#2]
When I try to install your module with Magisk 23.0 I get the following:

```
Updater process ended with ERROR: 255
Error installing zip file '/path/magisk-fusermount.zip'

```
This module is very critical for using rclone in Android 11 so very disappointed this is not working.

I have tried downloading it twice as well as installing it from two different locations, same result.

**Comment by mirsella** [comment]
![Screenshot_20210826-131657_Settings](https://user-images.githubusercontent.com/45905567/130953781-84ea8dde-a0fa-4e97-a77e-93fd6a03a3f2.png)

The module is working for me, can't replicate. 

> so very disappointed this is not working.

Please be kinder, I don't own you anything and I don't care if it doesn't work for you, it's not my problem.

**Comment by mirsella** [comment]
you can manually put the fusermount binary in the bin directory

**Comment by ioogithub** [comment]
> ![Screenshot_20210826-131657_Settings](https://user-images.githubusercontent.com/45905567/130953781-84ea8dde-a0fa-4e97-a77e-93fd6a03a3f2.png)
> 
> The module is working for me, can't replicate.
> 
> > so very disappointed this is not working.
> 
> Please be kinder, I don't own you anything and I don't care if it doesn't work for you, it's not my problem.

 I didn't intent for my expression of disappointment to be unkind or to imply that you work for or owe me anything. On the contrary, I greatly appreciate that you took the time to research the issue and offered to share a solution with others. I was trying express that because your module is very important to get the rclone working, I was disappointed at the result of not being able to install it, not at you for any reason. I understand you don't care if it works and I agree that it is not your problem. I regret sharing my experience with you, sorry.

**Comment by mirsella** [comment]
@ioogithub I'm not English, so maybe I'm wrong, but personally I see the word "disappointed" here as "I'm disappointed in you" even if it's grammatically not the case.

Now I would like to help you, but the module work for me and I couldn't find anything interesting on Google, sorry.
Your best bet I think would be to look into how to make a twrp flashable zip or a magisk module (it's not complicated) to install fusermount binary. You can manually put the file in /bin easily with apps like root browser, but every reboot you'll need to do it again.
